name: "Create release build for 2D-LipSync"
on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-event]

# OBI_AC_PAT_ORG is created by Obi and needs to be renewed every so often when it expires.
# send him to `https://github.com/settings/personal-access-tokens/798287` and have him click the regenerate button
# To update, have Obi navigate to "UNOMI Solutions -> settings -> secrets and stuff -> actions" and then update the value (note that 
# this is in the ORGANIZATION settings, while his token is in PERSONAL account settings)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v3

      - name: Download latest Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'UNOMi-Solutions/Unomi'
          regex: true
          file: ".*-build-mac.zip"
          token: ${{ secrets.OBI_AC_PAT_ORG }}

      - name: Unzip Files
        run: unzip "*-build-mac.zip" -d mac_build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Test
          prerelease: true
          files: |
            mac_build/*
          
